variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {
  default = "us-ashburn-1"
}
variable "compartment_ocid" {}
variable "DeploymentCompartment_display_name" {}
variable "DeploymentCompartment_description" {}
variable "Cas_Lhr_Prd_Vcn_display_name" {}
variable "Cas_Lhr_Prd_Vcn_dns_label" {}
variable "Cas_Lhr_Prd_Igw_display_name" {}
variable "Cas_Lhr_Prd_Igw_enabled" {}
variable "Cas_Lhr_Prd_Ngw_display_name" {}
variable "Cas_Lhr_Prd_Ngw_block_traffic" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Slt_display_name" {}
variable "Cas_Lhr_Prd_Pri_App_Slt_display_name" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Slt_display_name" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Slt_display_name" {}
variable "Cas_Lhr_Ppd_Pri_App_Slt_display_name" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Slt_display_name" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Rtb_display_name" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_display_name" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_02_destination" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_02_destination_type" {}
variable "Cas_Lhr_Prd_Pri_App_Rtb_route_rule_02_description" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_display_name" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_02_destination" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_02_destination_type" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Rtb_route_rule_02_description" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Rtb_display_name" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_display_name" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_02_destination" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_02_destination_type" {}
variable "Cas_Lhr_Ppd_Pri_App_Rtb_route_rule_02_description" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_display_name" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_01_destination" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_01_destination_type" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_01_description" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_02_destination" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_02_destination_type" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Rtb_route_rule_02_description" {}
variable "Okit_Rt007_display_name" {}
variable "Cas_Lhr_Prd_Sgw_display_name" {}
variable "Cas_Lhr_Prd_Sgw_service_name" {}
variable "Okit_Do001_display_name" {}
variable "Okit_Do001_dhcp_option_01_type" {}
variable "Okit_Do001_dhcp_option_01_server_type" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Sub_display_name" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Sub_cidr_block" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Sub_dns_label" {}
variable "Cas_Lhr_Prd_Pub_Lbr_Sub_prohibit_public_ip_on_vnic" {}
variable "Cas_Lhr_Prd_Pri_App_Sub_display_name" {}
variable "Cas_Lhr_Prd_Pri_App_Sub_cidr_block" {}
variable "Cas_Lhr_Prd_Pri_App_Sub_dns_label" {}
variable "Cas_Lhr_Prd_Pri_App_Sub_prohibit_public_ip_on_vnic" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Sub_display_name" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Sub_cidr_block" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Sub_dns_label" {}
variable "Cas_Lhr_Prd_Pri_Dbs_Sub_prohibit_public_ip_on_vnic" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Sub_display_name" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Sub_cidr_block" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Sub_dns_label" {}
variable "Cas_Lhr_Ppd_Pub_Lbr_Sub_prohibit_public_ip_on_vnic" {}
variable "Cas_Lhr_Ppd_Pri_App_Sub_display_name" {}
variable "Cas_Lhr_Ppd_Pri_App_Sub_cidr_block" {}
variable "Cas_Lhr_Ppd_Pri_App_Sub_dns_label" {}
variable "Cas_Lhr_Ppd_Pri_App_Sub_prohibit_public_ip_on_vnic" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Sub_display_name" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Sub_cidr_block" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Sub_dns_label" {}
variable "Cas_Lhr_Ppd_Pri_Dbs_Sub_prohibit_public_ip_on_vnic" {}
